POST http://localhost:3000/register 
Content-Type: application/json

{
    "username":"pina771",
    "password":"password123",
    "email":"pina771@gmail.com"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"pina771",
    "password": "password123"
}
###
GET  http://localhost:3000/api/users/pina771
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJpYXQiOjE2MzkwNzc4MTksImV4cCI6MTYzOTA3OTAxOX0.KF2Letcf-xZ7NaOSPF2quGUg1mNHphBcbcMutwnabNo
###
PUT http://localhost:3000/api/users/pina771
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJpYXQiOjE2MzkwNzA2NzF9.wrAcUtGAx52m8DH3vp09rPBAhq8D8BEFZbvGLgqS6qM

{
    "password": "newpassword123",
    "email":"newemail@shelby.org"
}
###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJpYXQiOjE2MzkwNzA2NzF9.wrAcUtGAx52m8DH3vp09rPBAhq8D8BEFZbvGLgqS6qM

{
    "title":"Test post from REST CLIENT",
    "content":"Howdy there, It's been a long time since we last saw each other."
}
###
PUT http://localhost:3000/api/posts/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJpYXQiOjE2MzkwNzA2NzF9.wrAcUtGAx52m8DH3vp09rPBAhq8D8BEFZbvGLgqS6qM

{
    "title":"Changed Title!",
    "content": "Whenever,wherever!"
}
###
DELETE http://localhost:3000/api/posts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJpYXQiOjE2MzkwNzA2NzF9.wrAcUtGAx52m8DH3vp09rPBAhq8D8BEFZbvGLgqS6qM
###
DELETE http://localhost:3000/api/users/pina771
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJpYXQiOjE2MzkwNzA2NzF9.wrAcUtGAx52m8DH3vp09rPBAhq8D8BEFZbvGLgqS6qM
