
POST http://localhost:3000/register 
Content-Type: application/json

{
    "username":"novi_korisnik",
    "password":"lozinka",
    "email":"novi_korisnik@gmail.com"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"novi_korisnik",
    "password": "lozinka"
}
###
###
GET  http://localhost:3000/api/posts
###
PUT http://localhost:3000/api/users/novi_korisnik
Content-Type: application/json
Authorization: Bearer 

{
    "password": "lozinka2",
    "email":"novi_novi_korisnik@gmail.com"
}
###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vdmlfa29yaXNuaWsiLCJpYXQiOjE2Mzk0OTIwOTMsImV4cCI6MTYzOTQ5OTI5M30.JLwec1jE0YzQIx-Vdwit2lKBwmMsKO9NxeHdroRBP3Q

{
    "title":"Test post from REST CLIENT",
    "content":"Howdy there, It's been a long time since we last saw each other."
}
###
PUT http://localhost:3000/api/posts/42
Content-Type: application/json
Authorization: Bearer 

{
    "title":"Changed Title!",
    "content": "Whenever,wherever!"
}
###
DELETE http://localhost:3000/api/posts/187
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vdmlfa29yaXNuaWsiLCJpYXQiOjE2Mzk0OTIwOTMsImV4cCI6MTYzOTQ5OTI5M30.JLwec1jE0YzQIx-Vdwit2lKBwmMsKO9NxeHdroRBP3Q
###
DELETE http://localhost:3000/api/users/novi_korisnik
Authorization: Bearer 