http://localhost:3000/api

###

http://localhost:3000/api/users

###

http://localhost:3000/api/users/jb7


###
http://localhost:3000/api/users/jb7/posts

### 

http://localhost:3000/api/posts

###

PUT http://localhost:3000/api/users/testuser123
Content-Type: application/json

{
    "password":"test123",
    "email":"test123@gmail.com"
}


